title: "Chun Huang"
author: "Chun Huang"
description: "Washington University in St Louis"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true          # adds a gray frame to the site
show_social: true 
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", file: "cv.md"}
  - {title: "CompactObject", url: "https://chunhuangphy.github.io/CompactObject/"}
  - {title: "Research", file: "research.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Inspire-HEP, url: "https://inspirehep.net/authors/2831773?ui-citation-summary=true"}
  - {title: Google Scholar, icon: google, url: "https://scholar.google.com/citations?user=oNADiKYAAAAJ&hl=en"}
  - {title: Mail, icon: envelope, url: "mailto:chun.h@wustl.edu"}
  - {title: Github, icon: github, url: "https://github.com/ChunHuangPhy"}
  - {title: Twitter/X, icon: twitter, url: "https://x.com/ChunHuang20"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
